### ISSUE TITLE
clang: argument list too long

### ISSUE THREAD

**Issue by dpo** [flame/libflame#3] opened 2015-05-10 18:14 UTC
On OSX with clang, I'm enabling `--enable-max-arg-list-hack` and that fixes the archiving of the static library. But clang still fails to build the dynamic library and errors out with the message "argument list too long". What's the way to circumvent that one?

Thanks.

**Comment by fgvanzee** [comment] 2015-05-11 16:15
The max-arg-list hack isn't implemented for shared object generation, just static archive. I'll work on a fix.

**Comment by sgsokol** [comment] 2018-01-16 14:46
I propose the following hack, first create a target.in file with all .o names to be put in .so library then link using @target.in :
```
$(file >$@.in,$?)
$(LINKER) -shared $(LDFLAGS) -o $@ @$@.in
```

**Comment by fgvanzee** [comment] 2018-01-16 23:36
Thanks for chiming in, @sgsokol. `-fPIC` is already included in the `CFLAGS` variable at compile-time. Also, `-shared` is included in `$(SOFLAGS)`, e.g.:
```
$(MK_BLIS_DLL): $(MK_BLIS_OBJS)
ifeq ($(BLIS_ENABLE_VERBOSE_MAKE_OUTPUT),yes)
    $(LINKER) $(SOFLAGS) $(LDFLAGS) -o $@ $?
else
    @echo "Dynamically linking $@"
    @$(LINKER) $(SOFLAGS) $(LDFLAGS) -o $@ $?
endif
```
As for your proposed hack, I'm unfamiliar with some of the syntax, specifically `@$@`. Would you  would you mind explaining what your modified lines do?

**Comment by sgsokol** [comment] 2018-01-17 09:23
'ld' command has a syntax '@file' that allows to read options from 'file' (here names of .o files). So if '$@' is 'libflame.so' then '@$@.in' will becomes '@libflame.so.in'.

**Comment by sgsokol** [comment] 2018-01-17 09:25
'ld' command has a syntax '@file' that allows to read options from 'file' (here names of .o files). So if '$@' is 'libflame.so' then '@$@.in' will becomes '@libflame.so.in'.

**Comment by sgsokol** [comment] 2018-01-17 12:49
Regarding `-fpic`, I don't know why by I had to add it by hand.
Another point, I was told that `-fPIC` is not available for all compilers. May be `-fpic` is better from this point of view (not sure as not checked by myself)

**Comment by fgvanzee** [comment] 2018-01-19 19:03
@sgsokol Thanks for your explanation vis-a-vis the `@file` notation for `ld`; I had forgotten that it accepted this syntax.

Now, could you explain the syntax of the first line?
```
$(file >$@.in,$?)
```
This looks like you're executing the `file` command via a `make` sub-shell, but the `file` command queries the file type of its arguments, so I don't see how that would be useful here.

**Comment by sgsokol** [comment] 2018-01-20 12:31
It's not a subshell but a gmake function. The first argument gives the operation to do (here it will expand to  `>libflame.so.in`, i.e. write to this file erasing its previous content if any), the second one is the content to write (here the list of updated .o objects)

**Comment by sgsokol** [comment] 2018-01-22 10:15
A thought afterword, it would be more appropriate to write `$(file >$@.in,$^)` as `$^` refers to all dependency objects, not only to the newer than the target ones (as `$?` does). For a static library, `$?` is perfectly working as we can just update new compilations in an existent archive while for shared library we have to add all objects at once at the moment of library creation.

**Comment by sgsokol** [comment] 2018-01-23 10:50
Thanks for the commit. As I have already mentioned it, I cannot get a .so if I don't add by hand `-fpic` or `-fPIC`. Here is my config and relevant output:
```
$ ./configure CFLAGS="-O3 -mtune=native -march=native" LDFLAGS=-L/opt/OpenBLAS/lib LIBS=-lopenblas --enable-dynamic-build --disable-static-build --enable-lapack2flame --enable-supermatrix --enable-memory-alignment=8 --enable-max-arg-list-hack

$ LC_ALL=C make -j6
...
Dynamically linking lib/x86_64-unknown-linux-gnu/libflame.so
/usr/bin/ld: obj/x86_64-unknown-linux-gnu/map/lapack2flamec/FLA_gebrd.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
obj/x86_64-unknown-linux-gnu/map/lapack2flamec/FLA_gebrd.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:417: recipe for target 'lib/x86_64-unknown-linux-gnu/libflame.so' failed
make: *** [lib/x86_64-unknown-linux-gnu/libflame.so] Error 1
```

**Comment by fgvanzee** [comment] 2018-01-23 18:32
@sgsokol Thanks for providing your `configure` command. I think I know what the problem is now.

You may or may not have been aware of this, but you don't need to set `CFLAGS` manually. `configure` will choose a set of flags that is suitable and near-optimal. Now, that said, if you **do** set `CFLAGS` manually, you are effectively telling `configure` that you want your `CFLAGS` to completely override any flags it would have chosen automatically. That is likely why you are having to add `-fPIC` yourself. If you simply let `configure` choose `CFLAGS` automatically, `-fPIC` will be included, provided that `--enable-dynamic-build` is given.

If you want to add to (rather than override) the `CFLAGS` that `configure` would normally use, you should specify those via `EXTRA_CFLAGS`. See `run-conf/run-configure.sh` for an example. (This script is also useful for running `configure` since (a) it naturally documents the way you most recently ran `configure`, and (b) it is easy to edit to your liking.)

**Comment by sgsokol** [comment] 2018-01-24 13:26
Right. With EXTRA_CFLAGS it works like a charm. I've could discover it my myself by more thorough reading of `configure --help` but I didn't. Thanks for making me discover this approach.
BTW, if an option `--enable-verbose-make-output` is activated then it makes fail the current hack with too long list of names for .so.

**Comment by fgvanzee** [comment] 2018-01-24 17:30
@sgsokol Yes, I forgot to extend the fix to the verbose case. Sorry, and thanks for pointing this out. fbb613a should take care of it.

**Closed** 2018-01-24 22:34 UTC
